name: flutter_rtmp_streaming_prototype
description: flutter_rtmp_streaming_prototyp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  # haishin tests: failed to build: error: invalid source release: 17
  # haishin_kit: ^0.10.0
  # permission_handler: any
  # audio_session: any

  # apivideo tests:
  apivideo_live_stream: ^1.1.1

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true




